name: 'Publish Allure reports to GitHub Pages'
description: 'Download Allure results, generate Allure 3 reports, and deploy to GitHub Pages.'

inputs:
  report-title:
    description: 'Title shown on the index page'
    required: true
  artifact-prefix-1:
    description: 'Primary artifact prefix, for example: playwright'
    required: true
  artifact-prefix-2:
    description: 'Optional second artifact prefix, for example: api'
    required: false
    default: ''
  artifact-prefix-3:
    description: 'Optional third artifact prefix, for example: selenium'
    required: false
    default: ''

outputs:
  page_url:
    description: 'Published GitHub Pages URL'
    value: ${{ steps.deployment.outputs.page_url }}

runs:
  using: 'composite'
  steps:
    - name: Download ${{ inputs.artifact-prefix-1 }} smoke Allure results
      continue-on-error: true
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-prefix-1 }}-smoke-allure-results
        path: allure-results/${{ inputs.artifact-prefix-1 }}/smoke

    - name: Download ${{ inputs.artifact-prefix-1 }} regression Allure results
      continue-on-error: true
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-prefix-1 }}-regression-allure-results
        path: allure-results/${{ inputs.artifact-prefix-1 }}/regression

    - name: Download ${{ inputs.artifact-prefix-2 }} smoke Allure results
      if: inputs.artifact-prefix-2 != ''
      continue-on-error: true
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-prefix-2 }}-smoke-allure-results
        path: allure-results/${{ inputs.artifact-prefix-2 }}/smoke

    - name: Download ${{ inputs.artifact-prefix-2 }} regression Allure results
      if: inputs.artifact-prefix-2 != ''
      continue-on-error: true
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-prefix-2 }}-regression-allure-results
        path: allure-results/${{ inputs.artifact-prefix-2 }}/regression

    - name: Download ${{ inputs.artifact-prefix-3 }} smoke Allure results
      if: inputs.artifact-prefix-3 != ''
      continue-on-error: true
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-prefix-3 }}-smoke-allure-results
        path: allure-results/${{ inputs.artifact-prefix-3 }}/smoke

    - name: Download ${{ inputs.artifact-prefix-3 }} regression Allure results
      if: inputs.artifact-prefix-3 != ''
      continue-on-error: true
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-prefix-3 }}-regression-allure-results
        path: allure-results/${{ inputs.artifact-prefix-3 }}/regression

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Generate Allure 3 reports
      shell: bash
      run: |
        set -euo pipefail
        mkdir -p pages

        prefixes=("${{ inputs.artifact-prefix-1 }}")
        if [ -n "${{ inputs.artifact-prefix-2 }}" ]; then
          prefixes+=("${{ inputs.artifact-prefix-2 }}")
        fi
        if [ -n "${{ inputs.artifact-prefix-3 }}" ]; then
          prefixes+=("${{ inputs.artifact-prefix-3 }}")
        fi

        for prefix in "${prefixes[@]}"; do
          for suite in smoke regression; do
            result_dir="allure-results/${prefix}/${suite}"
            if [ -d "$result_dir" ] && [ "$(ls -A "$result_dir")" ]; then
              npx --yes allure@3 generate "$result_dir" -o "pages/${prefix}/${suite}"
            fi
          done
        done

    - name: Create Pages index
      shell: bash
      run: |
        set -euo pipefail

        normalize_name() {
          echo "$1" | tr '[:lower:]' '[:upper:]' | sed 's/^API$/API/'
        }

        prefixes=("${{ inputs.artifact-prefix-1 }}")
        if [ -n "${{ inputs.artifact-prefix-2 }}" ]; then
          prefixes+=("${{ inputs.artifact-prefix-2 }}")
        fi
        if [ -n "${{ inputs.artifact-prefix-3 }}" ]; then
          prefixes+=("${{ inputs.artifact-prefix-3 }}")
        fi

        {
          echo '<!doctype html>'
          echo '<html lang="en">'
          echo '<head>'
          echo '  <meta charset="UTF-8" />'
          echo '  <meta name="viewport" content="width=device-width, initial-scale=1.0" />'
          echo "  <title>${{ inputs.report-title }}</title>"
          echo '</head>'
          echo '<body>'
          echo "  <h1>${{ inputs.report-title }}</h1>"

          for prefix in "${prefixes[@]}"; do
            label="$(normalize_name "$prefix")"
            echo "  <h2>${label}</h2>"
            echo '  <ul>'

            if [ -f "pages/${prefix}/smoke/index.html" ]; then
              echo "    <li><a href=\"./${prefix}/smoke/index.html\">Smoke report</a></li>"
            else
              echo '    <li>Smoke report: not available</li>'
            fi

            if [ -f "pages/${prefix}/regression/index.html" ]; then
              echo "    <li><a href=\"./${prefix}/regression/index.html\">Regression report</a></li>"
            else
              echo '    <li>Regression report: not available</li>'
            fi

            echo '  </ul>'
          done

          echo '</body>'
          echo '</html>'
        } > pages/index.html

    - name: Configure Pages
      uses: actions/configure-pages@v5

    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: pages

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
